### ISSUE TITLE
Import of cryptography is problematic because of dependencies

### ISSUE THREAD

**Issue by j4m-can** [j4m-can/hpct-library#4]
https://github.com/j4m-can/hpct-library/blob/e9e0ae6bb07163791b6d873a6f688f3513a2799d/lib/hpctlib/interface/codec.py#L14

The cryptography package has dependencies that must be supported on the target and are not available by default as they are not from the Python library.

**Comment by NucciTheBoss** [comment]
Given that I was able to close the issue in https://github.com/canonical/charmcraft/issues/858, I am going to close this issue out.

Everything works now since we can modify the configuration of `pip` with `override-build` to pull prebuilt wheels from private servers.
